export { default as Category } from "./category.svg?react";
export { default as Course } from "./course.svg?react";
export { default as Dashboard } from "./dashboard.svg?react";
export { default as Directory } from "./directory.svg?react";
export { default as Email } from "./email.svg?react";
export { default as EmptyCourse } from "./emptyCourse.svg?react";
export { default as HamburgerMenuClose } from "./hamburger-menu-close.svg?react";
export { default as HamburgerMenu } from "./hamburger-menu.svg?react";
export { default as InProgress } from "./in-progress.svg?react";
export { default as Blocked } from "./blocked.svg?react";
export { default as InputRoundedMarkerError } from "./input-rounded-marker-error.svg?react";
export { default as InputRoundedMarkerSuccess } from "./input-rounded-marker-success.svg?react";
export { default as InputRoundedMarker } from "./input-rounded-marker.svg?react";
export { default as LessonContent } from "./lesson-content.svg?react";
export { default as Lesson } from "./lesson.svg?react";
export { default as Logout } from "./logout.svg?react";
export { default as NotStartedRounded } from "./not-startet-rounded.svg?react";
export { default as Phone } from "./phone.svg?react";
export { default as Plus } from "./plus.svg?react";
export { default as PricingIllustration } from "./pricing-illustration.svg?react";
export { default as QuizStar } from "./quiz-star.svg?react";
export { default as AppLogo } from "./app-logo.svg?react";
export { default as AppSignet } from "./app-signet.svg?react";
export { default as Settings } from "./settings.svg?react";
export { default as StatusIllustration } from "./status-illustration.svg?react";
export { default as TrashIcon } from "./trash-icon.svg?react";
export { default as UploadIllustration } from "./upload-illustration.svg?react";
export { default as UploadImageIcon } from "./upload-image.svg?react";
export { default as User } from "./user.svg?react";
export { default as Warning } from "./warning.svg?react";
export { default as Admin } from "./admin.svg?react";
export { default as Hat } from "./hat.svg?react";
export { default as Multi } from "./multi.svg?react";
export { default as CertificateTrophy } from "./certificateTrophy.svg?react";
export { default as HandCoins } from "./hand-coins.svg?react";
export { default as Success } from "./success.svg?react";
export { default as CourseEmptyState } from "./course-empty-state.svg?react";
export { default as DragAndDropIcon } from "./drag-and-drop.svg?react";
export { default as Info } from "./info.svg?react";
export { default as Checkmark } from "./checkmark.svg?react";
export { default as Flame } from "./flame.svg?react";
export { default as FreeRight } from "./free-right.svg?react";
export { default as NoData } from "./no-data.svg?react";
export { default as Eye } from "./eye.svg?react";
export { default as Enroll } from "./enroll.svg?react";
export { default as IconX } from "./x-icon.svg?react";
export { default as Edit } from "./edit.svg?react";
export { default as X } from "./x.svg?react";
export { default as Smile } from "./smile.svg?react";
export { default as Send } from "./send.svg?react";
export { default as Google } from "./google.svg?react";
export { default as Microsoft } from "./microsoft.svg?react";
export { default as ExclamationTriangle } from "./exclamation-triangle.svg?react";
export { default as Ribbon } from "./ribbon.svg?react";
export { default as Megaphone } from "./megaphone.svg?react";
export { default as Slack } from "./slack.svg?react";
export { default as Search } from "./search.svg?react";
export { default as GlobalSearchMac } from "./CMD+K.svg?react";
export { default as GlobalSearchWin } from "./CTRL+K.svg?react";
export { default as Manage } from "./manage.svg?react";
export { default as Bell } from "./bell.svg?react";
export { default as KeyboardArrows } from "./keyboardArrows.svg?react";
export { default as KeyboardEnter } from "./keyboardEnter.svg?react";
export { default as KeyboardX } from "./keyboardX.svg?react";
export { default as Archive } from "./archive.svg?react";
export { default as Articles } from "./articles.svg?react";
export { default as Article } from "./article.svg?react";
export { default as News } from "./news.svg?react";
export { default as Calendar } from "./calendar.svg?react";
export { default as Group } from "./group.svg?react";
export { default as Library } from "./library.svg?react";
export { default as ChartNoAxes } from "./chart-no-axes.svg?react";
export { default as Target } from "./target.svg?react";
export { default as PanelLeftClose } from "./panel-left-close.svg?react";
export { default as PanelLeftOpen } from "./panel-left-open.svg?react";
export { default as WandSparkles } from "./wand-sparkles.svg?react";

export { SegmentedRing } from "./segmented-ring";

export * from "./lesson-types";
export * from "./question-types";
export * from "./arrows";
export * from "./actions";
export * from "./flags";
