import { emailTemplateFactory } from "./email-factory";
import BaseEmailTemplateTemplate from "./templates/BaseEmailTemplate";
export const BaseEmailTemplate = emailTemplateFactory(BaseEmailTemplateTemplate);
import CreatePasswordReminderEmailTemplate from "./templates/CreatePasswordReminderEmail";
export const CreatePasswordReminderEmail = emailTemplateFactory(CreatePasswordReminderEmailTemplate);
import FinishedCourseEmailTemplate from "./templates/FinishedCourseEmail";
export const FinishedCourseEmail = emailTemplateFactory(FinishedCourseEmailTemplate);
import MagicLinkEmailTemplate from "./templates/MagicLinkEmail";
export const MagicLinkEmail = emailTemplateFactory(MagicLinkEmailTemplate);
import NewUserEmailTemplate from "./templates/NewUserEmail";
export const NewUserEmail = emailTemplateFactory(NewUserEmailTemplate);
import PasswordRecoveryEmailTemplate from "./templates/PasswordRecoveryEmail";
export const PasswordRecoveryEmail = emailTemplateFactory(PasswordRecoveryEmailTemplate);
import UserAssignedToCourseEmailTemplate from "./templates/UserAssignedToCourseEmail";
export const UserAssignedToCourseEmail = emailTemplateFactory(UserAssignedToCourseEmailTemplate);
import UserFinishedChapterEmailTemplate from "./templates/UserFinishedChapterEmail";
export const UserFinishedChapterEmail = emailTemplateFactory(UserFinishedChapterEmailTemplate);
import UserFinishedCourseEmailTemplate from "./templates/UserFinishedCourseEmail";
export const UserFinishedCourseEmail = emailTemplateFactory(UserFinishedCourseEmailTemplate);
import UserFirstLoginEmailTemplate from "./templates/UserFirstLoginEmail";
export const UserFirstLoginEmail = emailTemplateFactory(UserFirstLoginEmailTemplate);
import UserInviteEmailTemplate from "./templates/UserInviteEmail";
export const UserInviteEmail = emailTemplateFactory(UserInviteEmailTemplate);
import UserLongInactivityEmailTemplate from "./templates/UserLongInactivityEmail";
export const UserLongInactivityEmail = emailTemplateFactory(UserLongInactivityEmailTemplate);
import UserShortInactivityEmailTemplate from "./templates/UserShortInactivityEmail";
export const UserShortInactivityEmail = emailTemplateFactory(UserShortInactivityEmailTemplate);
import WelcomeEmailTemplate from "./templates/WelcomeEmail";
export const WelcomeEmail = emailTemplateFactory(WelcomeEmailTemplate);